improved testing and support for type parameterisation

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,8 +1,31 @@
-.PHONY: clean
-clean:
-	rm -rf *~
+TESTFILES=$(shell ls -1 *.sig)
+OUTFILES=$(TESTFILES:%.sig=%.out)
+RESFILES=$(TESTFILES:%.sig=%.res)
 
 .PHONY: test
-test:
-	make -C .. smlexpose
-	../smlexpose -v test01.sig
+test: $(RESFILES)
+	@cat $(RESFILES)
+	@echo "-------T E S T --- R E P O R T-------"
+	@echo "Tests succeeded:   `grep "OK" $(RESFILES) | wc -l` /`grep "Test" $(RESFILES) | wc -l`"
+	@echo "Test errors:       `grep "ERR" $(RESFILES) | wc -l` /`grep "Test" $(RESFILES) | wc -l`"
+	@echo "-------------------------------------"
+	@exit `grep "ERR" $(RESFILES) | wc -l`
+
+.PHONY: clean
+clean:
+	rm -rf *~ *.out *.res
+
+%.out: %.sig
+	../smlexpose -v $< > $@
+
+%.res: %.out
+	@(diff -aq $< $<.ok > /dev/null 2>&1; \
+         if [ $$? -eq 0 ]; then \
+             echo "Test $*.sig: OK" > $@ \
+         ; else \
+             if [ -e $<.ok ]; then \
+                echo "Test $*.sig: *** ERR: file $< differs from $<.ok ***" > $@ \
+             ; else \
+                echo "Test $*.sig: *** ERR: file $<.ok does not exist ***" > $@ \
+             ; fi \
+         ; fi)
